### ISSUE TITLE
Image does not recognize Docker memory limits

### ISSUE THREAD

**Issue by Xalaxis** [fkrauthan/sheepit-docker#1]
If a memory limit is set with `--memory`, the container will exceed this and cause the process to be killed.

Ideally the container would either detect this memory limit and use the value manually, or allow the Sheepit memory limit to be set from the environment variables.

**Comment by fkrauthan** [comment]
If you know how feel free to create a pull request. I am happy to merge that in.

**Comment by Xalaxis** [comment]
So I had a shot at implementing this today and I think I've got a solution, but for some reason my local SheepIt client gets stuck in a never-ending performance testing loop even without any tweaks.  I don't suppose this is something you've run into before?

**Comment by fkrauthan** [comment]
No I never had that happening before. Btw I thought this two start options together `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` should allow Java to auto detect the memory limit set for the docker container.

**Comment by Xalaxis** [comment]
I think the problem is that those limits only apply to the Java application itself, a.k.a the SheepIt client.  The spawned blender instance only obeys the memory limit set via the -memory parameter.

**Comment by Xalaxis** [comment]
It appears my solution was working R.E. memory usage, and actually it was the whole client that was broken giving me the problem I described above.  I've opened a new issue, #3
