### ISSUE TITLE
New client available

### ISSUE THREAD

**Issue by Xalaxis** [fkrauthan/sheepit-docker#11]
Client version sheepit-client-6.21338.0 is now available (I believe with support for Blender 3.0!)

**Comment by fkrauthan** [comment]
Version `6.21338.0` should be out soon. Including an upgrade to Java 11 (as if I understand it correctly that is the new minimum java version). Let me know if there are any issues.

**Comment by Xalaxis** [comment]
Thanks for having a look 🙂 

Getting a `Unrecognized VM option 'UseCGroupMemoryLimitForHeap'` because native support was added in Java 11. I think you should just be able to remove `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` and it should work :)

**Comment by fkrauthan** [comment]
Oh good catch. Yeah Java 11 detects the docker memory limits out of the box.

**Comment by fkrauthan** [comment]
A new version should be deployed.

**Comment by Xalaxis** [comment]
That's working, thanks! :)
