### ISSUE TITLE
Container broken in infinite "Check computer strength." loop

### ISSUE THREAD

**Issue by Xalaxis** [fkrauthan/sheepit-docker#3]
Uh oh, it looks like #2 has broken the container.  Now all my instances are getting the "Check computer strength." project infinitely.

**Comment by fkrauthan** [comment]
Hmm that is strange since you are correct that it is the latest sheepit version. Did you check with the sheepit team if they are aware of a bug in that version?

**Comment by Xalaxis** [comment]
Just doing some local debug testing and then I'll file a bug 👍

**Comment by Xalaxis** [comment]
Issue filed at https://github.com/laurent-clouet/sheepit-client/issues/278

**Comment by Xalaxis** [comment]
I've just tested under Linux (WSL), and it seems to be working fine, so I wonder if it's container-specific or even just an issue with this container somehow.

**Comment by Xalaxis** [comment]
Update: It's a [fixed upstream issue](https://github.com/laurent-clouet/sheepit-client/pull/277).  Until the next release is available I suggest falling back to an older version (#4)

**Comment by fkrauthan** [comment]
I just updated the image to new sheepit client version `6.2020.0`. Can you please let me know if that works for you. The new images should appear on Docker Hub shortly.

**Comment by Xalaxis** [comment]
Yup, I can confirm that fixes the issue!
