### ISSUE TITLE
Add support for GPU enabled containers

### ISSUE THREAD

**Issue by mikef-nl** [fkrauthan/sheepit-docker#7]
Might be an idea to add a environment variable for CPU or GPU compute method:
-gpu CUDA_0 -compute-method GPU as an example.
I'm currently testing this with the GPU enabled container instances in Azure.

**Comment by fkrauthan** [comment]
Feel free to provide a pull request. I unfortunately have no experience with GPU enabled containers.

**Comment by mikef-nl** [comment]
As requested https://github.com/fkrauthan/sheepit-docker/pull/8 . Also worth reading https://docs.microsoft.com/en-us/azure/container-instances/container-instances-gpu

**Comment by fkrauthan** [comment]
Thank you very much. I just tagged version `6.20304.0.1` which should be available shortly on docker hub.
